export type Models =
  | 'tag'
  | 'concept'
  | 'goal'
  | 'dependency'
  | 'conceptsettings'
  | 'globalresource'
  | 'conceptresource'
  | 'resourceloaction'
  | 'graph'
  | 'graphsettings'
  | 'targetgraph'
